name: Hexo Deploy

# 只监听 hexo 分支的改动
on:
  push:
    branches:
      - hexo

# 自定义环境变量
env:
  POST_ASSET_IMAGE_CDN: true

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # 获取博客源码和主题
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: hexo

      # 这里用的是 Node.js 14.x
      - name: Set up Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '14'

      # 设置 yarn 缓存，npm 的话可以看 actions/cache@v2 的文档示例
      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn cache dir)"

      - name: Use yarn cache
        uses: actions/cache@v2
        id: yarn-cache
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      # 安装依赖
      - name: Install dependencies
        run: |
          rm -f .yarnclean
          yarn add hexo-cli
          yarn add hexo-util
          yarn add hexo-abbrlink
          yarn add hexo-wordcount
          yarn add hexo-generator-sitemap
          yarn add hexo-generator-feed
          yarn add hexo-all-minifier
          yarn add hexo-static-cos
          yarn add hexo-filter-nofollow
          yarn install --prefer-offline --frozen-lockfile

       # 生成博客
      - name: Generate
        run: |         
          rm -rf ./public
          npx hexo clean
          npx hexo generate

      # 从之前设置的 secret 获取部署私钥
      - name: Set up environment
        env:
          DEPLOY_KEY: ${{ secrets.DEPLOY_KEY }}
          GIT_NAME: ${{ secrets.GIT_NAME }}
          GIT_EMAIL: ${{ secrets.GIT_EMAIL }}
        run: |
          sudo timedatectl set-timezone "Asia/Shanghai"
          mkdir -p ~/.ssh
          echo "$DEPLOY_KEY" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan github.com >> ~/.ssh/known_hosts
          git config --global user.name "$GIT_NAME"
          git config --global user.email "$GIT_EMAIL"

      # 部署
      - name: Deploy
        run: |
          npx hexo deploy
